name: Lint and unit tests
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: 'true'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --enable goimports
  tests:
     name: Tests
     runs-on: ubuntu-latest
     env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
     steps:
     - name: Check out code
       uses: actions/checkout@v2
       with:
        fetch-depth: 1
     - name: Setup Go
       uses: actions/setup-go@v3
       with:
        go-version: 1.17
     - run: |
         GOPROXY=direct,https://proxy.golang.org GOSUMDB=off GO111MODULE=on go test -v ./...
